import 'package:flutter/material.dart';
import 'package:newest_insurance/constants_regulator/insurance_company_list.dart';
import 'package:newest_insurance/information/insurance_company_info.dart';
import 'package:charts_flutter/flutter.dart' as charts;

final List<InsuranceCompany> insuranceCompanies = [

  InsuranceCompany(
    score: 500,
    fraud: insuranceCompanyList[0]['fraud cases'],
    name: 'Masr Insurance',
    barColor: charts.ColorUtil.fromDartColor(Colors.blue),
    claims: 50,
    ageClaims: [
      {'20-40': 10},
      {'40-60': 20},
      {'60-80': 30},
      {'Below 20': 28},
    ],
    complains: 16,
    carModels: 10,
    rejectedClaims: 20,
    policiesIssued: 80,
    canceledPolicies: 10,
    complainsBrokers: 3,
    insuranceRate: 1000,
    locations: ["Fifth Settlement", "Masr el gedida", "Maadi"],
    yearsInBusiness: 10,
    shareHolderNames: ["Ahmed", "Omar", "Youssef"],
    complainsClients: 13,
    totalPremiums: 1000000,
  ),
  InsuranceCompany(
    score: 800,
    fraud: insuranceCompanyList[1]['fraud cases'],
    name: 'Cairo Insurance',
    barColor: charts.ColorUtil.fromDartColor(Colors.blue),
    ageClaims: [
      {'20-40': 10},
      {'40-60': 20},
      {'60-80': 30},
      {'Below 20': 28},
    ],
    claims: 20,
    complains: 26,
    carModels: 14,
    rejectedClaims: 29,
    policiesIssued: 108,
    canceledPolicies: 10,
    complainsBrokers: 3,
    insuranceRate: 1000,
    locations: ["Fifth Settlement", "Masr el gedida", "Maadi"],
    yearsInBusiness: 10,
    shareHolderNames: ["Ahmed", "Omar", "Youssef"],
    complainsClients: 13,
    totalPremiums: 1000000,
  ),
  InsuranceCompany(
      score: 1000,
      name: 'Alex Insurance',
      fraud: insuranceCompanyList[2]['fraud cases'],
      claims: 40,
      barColor: charts.ColorUtil.fromDartColor(Colors.blue),
      complains: 8,
      carModels: 5,
      rejectedClaims: 6,
      policiesIssued: 60,
      canceledPolicies: 10,
      complainsBrokers: 3,
      insuranceRate: 1000,
      locations: ["Fifth Settlement", "Masr el gedida", "Maadi"],
      yearsInBusiness: 10,
      shareHolderNames: ["Ahmed", "Omar", "Youssef"],
      complainsClients: 13,
      totalPremiums: 1000000,
      ageClaims: [
        {'20-40': 10},
        {'40-60': 20},
        {'60-80': 30},
        {'Below 20': 28},
      ]

  ),
  InsuranceCompany(
      score: 400,
      name: 'Allianz Insurance',
      fraud: insuranceCompanyList[3]['fraud cases'],
      claims: 80,
      barColor: charts.ColorUtil.fromDartColor(Colors.blue),
      complains: 4,
      carModels: 24,
      rejectedClaims: 13,
      policiesIssued: 120,
      canceledPolicies: 10,
      complainsBrokers: 3,
      insuranceRate: 1000,
      locations: ["Fifth Settlement", "Masr el gedida", "Maadi"],
      yearsInBusiness: 10,
      shareHolderNames: ["Ahmed", "Omar", "Youssef"],
      complainsClients: 13,
      totalPremiums: 1000000,
      ageClaims: [
        {'20-40': 10},
        {'40-60': 20},
        {'60-80': 30},
        {'Below 20': 28},
      ]
  ),
];